### ISSUE TITLE
running WALT on Mac and/or optimize memory

### ISSUE THREAD

**Issue by antoine4ucsd** [smithlabcode/walt#25]
Hi,
I am trying to run WALT on Mac or to optimize memory allocation on my linux machine:

**ON MY MAC:**
When I run
`makedb -c ./split_chr_ref_folder -o hg19.masked.dbindex`
I got the following error:
`dyld: lazy symbol binding failed: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/antoinechaillon/Documents/walt/bin/makedb (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /Users/antoinechaillon/Documents/walt/bin/makedb (which was built for Mac OS X 10.11)
  Expected in: /usr/lib/libstdc++.6.dylib`

Any chance WALT can work on MacOS?

**WITH LINUX:**
I've installed WALT on a linux machine but when I run 
`makedb -c ./split_chr_ref_folder -o hg19.masked.dbindex`
I have memory problem:
`**[COUNT BUCKET SIZE]
[NOTICE: ERASE THE BUCKET 4194303 SINCE ITS SIZE IS 934420]
[NOTICE: ERASE THE BUCKET 12582911 SINCE ITS SIZE IS 709199]
[NOTICE: ERASE THE BUCKET 13631487 SINCE ITS SIZE IS 850510]
[NOTICE: ERASE THE BUCKET 15728639 SINCE ITS SIZE IS 653272]
[NOTICE: ERASE THE BUCKET 15990783 SINCE ITS SIZE IS 791404]
[NOTICE: ERASE THE BUCKET 16515071 SINCE ITS SIZE IS 610398]
[NOTICE: ERASE THE BUCKET 16580607 SINCE ITS SIZE IS 774223]
[NOTICE: ERASE THE BUCKET 16711679 SINCE ITS SIZE IS 614458]
[NOTICE: ERASE THE BUCKET 16728063 SINCE ITS SIZE IS 759120]
[NOTICE: ERASE THE BUCKET 16760831 SINCE ITS SIZE IS 591405]
[NOTICE: ERASE THE BUCKET 16764927 SINCE ITS SIZE IS 735242]
[NOTICE: ERASE THE BUCKET 16773119 SINCE ITS SIZE IS 580192]
[NOTICE: ERASE THE BUCKET 16774143 SINCE ITS SIZE IS 727159]
[NOTICE: ERASE THE BUCKET 16776191 SINCE ITS SIZE IS 604228]
[NOTICE: ERASE THE BUCKET 16776447 SINCE ITS SIZE IS 725546]
[NOTICE: ERASE THE BUCKET 16776959 SINCE ITS SIZE IS 593534]
[NOTICE: ERASE THE BUCKET 16777023 SINCE ITS SIZE IS 732571]
[NOTICE: ERASE THE BUCKET 16777151 SINCE ITS SIZE IS 577419]
[NOTICE: ERASE THE BUCKET 16777167 SINCE ITS SIZE IS 762077]
[NOTICE: ERASE THE BUCKET 16777199 SINCE ITS SIZE IS 627084]
[NOTICE: ERASE THE BUCKET 16777203 SINCE ITS SIZE IS 834068]
[NOTICE: ERASE THE BUCKET 16777211 SINCE ITS SIZE IS 654082]
[NOTICE: ERASE THE BUCKET 16777212 SINCE ITS SIZE IS 894219]
[NOTICE: ERASE THE BUCKET 16777214 SINCE ITS SIZE IS 749400]
[NOTICE: ERASE THE BUCKET 16777215 SINCE ITS SIZE IS 3860849]
[HASH TO BUCKET]
ERROR: could not allocate memory**`

Any chance we can optimize the memory allocation???
thank you so much ++

**Comment by andrewdavidsmith** [comment]
Hi Antoine.

Can you please contact me directly about this?

Andrew

**Comment by antoine4ucsd** [comment]
Hi Andrew,
any chance you can help me with the issue I encountered? 
Do you need more info?

I am trying to prepare a human genome for methylation screening 
(see draft of protocol from ROCHE attached, p8)


thank you++


Antoine Chaillon M.D., Ph.D.
Center For Aids Research (CFAR)
Division of Infectious Diseases,
UCSD & VA San Diego Healthcare System 
Stein Clinical Research Building #325
University of California San Diego 
9500 Gilman Drive
La Jolla CA, 92093-0679
(619) 928-1842

**Comment by andrewdavidsmith** [comment]
How much memory on the linux machine?

Regarding the mac version, I can’t tell anything about how you compiled the software. Can you please show me the output of compiling it, and also the output of your “env” command and the result of “gcc —version”?

Andrew

On Jun 29, 2017, at 7:30 AM, antoine <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Andrew,
any chance you can help me with the issue I encountered?
Do you need more info?

I am trying to prepare a human genome for methylation screening
(see draft of protocol from ROCHE attached, p8)


thank you++


Antoine Chaillon M.D., Ph.D.
Center For Aids Research (CFAR)
Division of Infectious Diseases,
UCSD & VA San Diego Healthcare System
Stein Clinical Research Building #325
University of California San Diego
9500 Gilman Drive
La Jolla CA, 92093-0679
(619) 928-1842

**Comment by andrewdavidsmith** [comment]
Please contact me directly about this by email rather than using the github interface.


On Jun 29, 2017, at 7:30 AM, antoine <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Andrew,
any chance you can help me with the issue I encountered?
Do you need more info?

I am trying to prepare a human genome for methylation screening
(see draft of protocol from ROCHE attached, p8)


thank you++


Antoine Chaillon M.D., Ph.D.
Center For Aids Research (CFAR)
Division of Infectious Diseases,
UCSD & VA San Diego Healthcare System
Stein Clinical Research Building #325
University of California San Diego
9500 Gilman Drive
La Jolla CA, 92093-0679
(619) 928-1842

**Comment by antoine4ucsd** [comment]
for the linux machine: only 4Go (that’s why I tried to move to my mac)

On my mac, I downloaded walt from github (git), and the run make all / make install (the latter does not seem to do anything on Mac - any alternative command?)
$ git clone https://github.com/smithlabcode/walt.git
then I ran the following:
$ make all
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o reference.o reference.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -o makedb makedb.cpp reference.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o mapping.o mapping.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o paired.o paired.cpp  -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -o walt walt.cpp reference.o mapping.o paired.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
achaillon-2:walt antoinechaillon$ make install
achaillon-2:walt antoinechaillon$ 
(looks like make install doesn’t change anything)
Resulting in:
$ ls
FAQ.md		LICENSE		Makefile	README.md	bin		doc		src

Below are some details about my Mac:
 
gcc --version
gcc (GCC) 4.8.5


ENV:
achaillon-2:~ antoinechaillon$ env
TERM_PROGRAM=Apple_Terminal
STAMPY_BIN=/Users/antoinechaillon/Documents/hivfullength/stampy-1.0.28/stampy.py
SHELL=/bin/bash
TERM=xterm-256color
SPADES_BIN=/Users/antoinechaillon/anaconda2/share/spades-3.7.0-0/bin/spades
TMPDIR=/var/folders/xc/4sd_6xyd1k789nct2fvcnb4c0000gn/T/
SEQANPATH=/Users/antoinechaillon/Documents/seqan/include/seqan
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.cTT57haeLB/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=A1218C10-4C79-48F8-AC7D-D5A3295F18A9
USER=antoinechaillon
RAZERS3_BIN=/Users/antoinechaillon/Documents/razers3-3.5.3-Mac-x86_64/bin/razers3
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.UBbzuFTNsl/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
BWA_BIN=/Users/antoinechaillon/Documents/bwa/bwa
FASTTREE_BIN=/Users/antoinechaillon/Documents/HIV/TOOLS/fastree/FastTree
PATH=/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/antoinechaillon/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/antoinechaillon
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/antoinechaillon
HIVWHOLESEQ_ROOT_DATA_FOLDER=/Volumes/LACIE SHARE/
PYTHONPATH=/Users/antoinechaillon/Documents/hivfullength
LOGNAME=antoinechaillon
DISPLAY=/private/tmp/com.apple.launchd.lMI3BVnLLU/org.macosforge.xquartz:0
_=/usr/bin/env

**Comment by andrewdavidsmith** [comment]
This is a helpful start. I’ll respond as soon as you email me directly rather than through github.

Andrew

On Jun 29, 2017, at 7:56 AM, antoine <notifications@github.com<mailto:notifications@github.com>> wrote:

for the linux machine: only 4Go (that’s why I tried to move to my mac)

On my mac, I downloaded walt from github (git), and the run make all / make install (the latter does not seem to do anything on Mac - any alternative command?)
$ git clone https://github.com/smithlabcode/walt.git
then I ran the following:
$ make all
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o reference.o reference.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -o makedb makedb.cpp reference.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o mapping.o mapping.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -c -o paired.o paired.cpp -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
g++ -Wall -O3 -fPIC -fmessage-length=50 -fopenmp -D SEEDPATTERN3 -arch x86_64 -o walt walt.cpp reference.o mapping.o paired.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_os.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/smithlab_utils.o /Users/antoinechaillon/Documents/walt/src/smithlab_cpp/OptionParser.o -I/Users/antoinechaillon/Documents/walt/src/smithlab_cpp
achaillon-2:walt antoinechaillon$ make install
achaillon-2:walt antoinechaillon$
(looks like make install doesn’t change anything)
Resulting in:
$ ls
FAQ.md LICENSE Makefile README.md bin doc src

Below are some details about my Mac:

gcc --version
gcc (GCC) 4.8.5


ENV:
achaillon-2:~ antoinechaillon$ env
TERM_PROGRAM=Apple_Terminal
STAMPY_BIN=/Users/antoinechaillon/Documents/hivfullength/stampy-1.0.28/stampy.py
SHELL=/bin/bash
TERM=xterm-256color
SPADES_BIN=/Users/antoinechaillon/anaconda2/share/spades-3.7.0-0/bin/spades
TMPDIR=/var/folders/xc/4sd_6xyd1k789nct2fvcnb4c0000gn/T/
SEQANPATH=/Users/antoinechaillon/Documents/seqan/include/seqan
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.cTT57haeLB/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=A1218C10-4C79-48F8-AC7D-D5A3295F18A9
USER=antoinechaillon
RAZERS3_BIN=/Users/antoinechaillon/Documents/razers3-3.5.3-Mac-x86_64/bin/razers3
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.UBbzuFTNsl/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
BWA_BIN=/Users/antoinechaillon/Documents/bwa/bwa
FASTTREE_BIN=/Users/antoinechaillon/Documents/HIV/TOOLS/fastree/FastTree
PATH=/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/Users/antoinechaillon/anaconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
PWD=/Users/antoinechaillon
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/antoinechaillon
HIVWHOLESEQ_ROOT_DATA_FOLDER=/Volumes/LACIE SHARE/
PYTHONPATH=/Users/antoinechaillon/Documents/hivfullength
LOGNAME=antoinechaillon
DISPLAY=/private/tmp/com.apple.launchd.lMI3BVnLLU/org.macosforge.xquartz:0
_=/usr/bin/env
